version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Adding javaws-openjdk repo
      - add-apt-repository ppa:maarten-fonville/ppa
      - echo Updating packages
      - apt-get -y update
      - echo Purging OpenJFX
      - apt purge openjfx
      - echo Fetching OpenJFX
      - apt-get -y install openjfx=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2
      - echo Fetching javaws-openjdk
      - apt-get -y install icedtea-8-plugin
      - echo Linking alternative
      - rm /etc/alternatives/javaws
      - ln -s /usr/lib/jvm/java-8-openjdk-i386/jre/bin/javaws /etc/alternatives/.
  build:
    commands:
      - echo Build started on `date`
      - chmod +x aws_scripts/build.sh
      - aws_scripts/build.sh mvn -B package
  post_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - aws_scripts/**/*
    - API/target/api/**/*
    - FrontEndv8/dist/FrontEndv8/**/*
