//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for dt.DocumentData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dt.DocumentData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="reference" type="{http://www.e-mis.com/emisopen}dt.url"/&gt;
 *         &lt;element name="documentData" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="encoding" type="{http://www.e-mis.com/emisopen}voc.BinaryDataEncoding" /&gt;
 *       &lt;attribute name="compression" type="{http://www.e-mis.com/emisopen}voc.CompressionAlgorithm" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dt.DocumentData", propOrder = {
    "reference",
    "documentData"
})
public class DtDocumentData {

    @XmlSchemaType(name = "anyURI")
    protected String reference;
    protected String documentData;
    @XmlAttribute(name = "encoding")
    protected VocBinaryDataEncoding encoding;
    @XmlAttribute(name = "compression")
    protected VocCompressionAlgorithm compression;

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    /**
     * Gets the value of the documentData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentData() {
        return documentData;
    }

    /**
     * Sets the value of the documentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentData(String value) {
        this.documentData = value;
    }

    /**
     * Gets the value of the encoding property.
     * 
     * @return
     *     possible object is
     *     {@link VocBinaryDataEncoding }
     *     
     */
    public VocBinaryDataEncoding getEncoding() {
        return encoding;
    }

    /**
     * Sets the value of the encoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocBinaryDataEncoding }
     *     
     */
    public void setEncoding(VocBinaryDataEncoding value) {
        this.encoding = value;
    }

    /**
     * Gets the value of the compression property.
     * 
     * @return
     *     possible object is
     *     {@link VocCompressionAlgorithm }
     *     
     */
    public VocCompressionAlgorithm getCompression() {
        return compression;
    }

    /**
     * Sets the value of the compression property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocCompressionAlgorithm }
     *     
     */
    public void setCompression(VocCompressionAlgorithm value) {
        this.compression = value;
    }

}
