//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>Java class for dt.PostcodeData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dt.PostcodeData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CountryCode"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PCTCode"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TownsendScore"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IMD"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="HouseInPoorCondition"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CombinedAirQualityIndex"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="NitrogenDioxide"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PM10"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SulphurDioxide"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Benzene"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RuralityEnglandWales"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RuralityScotland"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Version"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dt.PostcodeData", propOrder = {
    "countryCode",
    "pctCode",
    "townsendScore",
    "imd",
    "houseInPoorCondition",
    "combinedAirQualityIndex",
    "nitrogenDioxide",
    "pm10",
    "sulphurDioxide",
    "benzene",
    "ruralityEnglandWales",
    "ruralityScotland",
    "version"
})
public class DtPostcodeData {

    @XmlElement(name = "CountryCode", required = true)
    protected String countryCode;
    @XmlElement(name = "PCTCode", required = true)
    protected String pctCode;
    @XmlElement(name = "TownsendScore", required = true)
    protected BigDecimal townsendScore;
    @XmlElement(name = "IMD", required = true)
    protected BigDecimal imd;
    @XmlElement(name = "HouseInPoorCondition", required = true)
    protected BigDecimal houseInPoorCondition;
    @XmlElement(name = "CombinedAirQualityIndex", required = true)
    protected BigDecimal combinedAirQualityIndex;
    @XmlElement(name = "NitrogenDioxide", required = true)
    protected BigDecimal nitrogenDioxide;
    @XmlElement(name = "PM10", required = true)
    protected BigDecimal pm10;
    @XmlElement(name = "SulphurDioxide", required = true)
    protected BigDecimal sulphurDioxide;
    @XmlElement(name = "Benzene", required = true)
    protected BigDecimal benzene;
    @XmlElement(name = "RuralityEnglandWales", required = true)
    protected String ruralityEnglandWales;
    @XmlElement(name = "RuralityScotland", required = true)
    protected String ruralityScotland;
    @XmlElement(name = "Version")
    protected int version;

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the pctCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCTCode() {
        return pctCode;
    }

    /**
     * Sets the value of the pctCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCTCode(String value) {
        this.pctCode = value;
    }

    /**
     * Gets the value of the townsendScore property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTownsendScore() {
        return townsendScore;
    }

    /**
     * Sets the value of the townsendScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTownsendScore(BigDecimal value) {
        this.townsendScore = value;
    }

    /**
     * Gets the value of the imd property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIMD() {
        return imd;
    }

    /**
     * Sets the value of the imd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIMD(BigDecimal value) {
        this.imd = value;
    }

    /**
     * Gets the value of the houseInPoorCondition property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHouseInPoorCondition() {
        return houseInPoorCondition;
    }

    /**
     * Sets the value of the houseInPoorCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHouseInPoorCondition(BigDecimal value) {
        this.houseInPoorCondition = value;
    }

    /**
     * Gets the value of the combinedAirQualityIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCombinedAirQualityIndex() {
        return combinedAirQualityIndex;
    }

    /**
     * Sets the value of the combinedAirQualityIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCombinedAirQualityIndex(BigDecimal value) {
        this.combinedAirQualityIndex = value;
    }

    /**
     * Gets the value of the nitrogenDioxide property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNitrogenDioxide() {
        return nitrogenDioxide;
    }

    /**
     * Sets the value of the nitrogenDioxide property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNitrogenDioxide(BigDecimal value) {
        this.nitrogenDioxide = value;
    }

    /**
     * Gets the value of the pm10 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPM10() {
        return pm10;
    }

    /**
     * Sets the value of the pm10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPM10(BigDecimal value) {
        this.pm10 = value;
    }

    /**
     * Gets the value of the sulphurDioxide property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSulphurDioxide() {
        return sulphurDioxide;
    }

    /**
     * Sets the value of the sulphurDioxide property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSulphurDioxide(BigDecimal value) {
        this.sulphurDioxide = value;
    }

    /**
     * Gets the value of the benzene property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBenzene() {
        return benzene;
    }

    /**
     * Sets the value of the benzene property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBenzene(BigDecimal value) {
        this.benzene = value;
    }

    /**
     * Gets the value of the ruralityEnglandWales property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuralityEnglandWales() {
        return ruralityEnglandWales;
    }

    /**
     * Sets the value of the ruralityEnglandWales property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuralityEnglandWales(String value) {
        this.ruralityEnglandWales = value;
    }

    /**
     * Gets the value of the ruralityScotland property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuralityScotland() {
        return ruralityScotland;
    }

    /**
     * Sets the value of the ruralityScotland property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuralityScotland(String value) {
        this.ruralityScotland = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public int getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(int value) {
        this.version = value;
    }

}
