//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dt.TimeRange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dt.TimeRange"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice minOccurs="0"&gt;
 *         &lt;element name="baseLow"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="low" type="{http://www.e-mis.com/emisopen}dt.DatePart"/&gt;
 *                   &lt;choice minOccurs="0"&gt;
 *                     &lt;element name="width" type="{http://www.e-mis.com/emisopen}dt.Duration" minOccurs="0"/&gt;
 *                     &lt;element name="high" type="{http://www.e-mis.com/emisopen}dt.DatePart" minOccurs="0"/&gt;
 *                   &lt;/choice&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="baseHigh"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="high" type="{http://www.e-mis.com/emisopen}dt.DatePart"/&gt;
 *                   &lt;choice minOccurs="0"&gt;
 *                     &lt;element name="width" type="{http://www.e-mis.com/emisopen}dt.Duration" minOccurs="0"/&gt;
 *                     &lt;element name="low" type="{http://www.e-mis.com/emisopen}dt.DatePart" minOccurs="0"/&gt;
 *                   &lt;/choice&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="baseCenter"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="center" type="{http://www.e-mis.com/emisopen}dt.DatePart"/&gt;
 *                   &lt;element name="width" type="{http://www.e-mis.com/emisopen}dt.Duration" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dt.TimeRange", propOrder = {
    "baseLow",
    "baseHigh",
    "baseCenter"
})
public class DtTimeRange {

    protected BaseLow baseLow;
    protected BaseHigh baseHigh;
    protected BaseCenter baseCenter;

    /**
     * Gets the value of the baseLow property.
     *
     * @return
     *     possible object is
     *     {@link BaseLow }
     *
     */
    public BaseLow getBaseLow() {
        return baseLow;
    }

    /**
     * Sets the value of the baseLow property.
     *
     * @param value
     *     allowed object is
     *     {@link BaseLow }
     *
     */
    public void setBaseLow(BaseLow value) {
        this.baseLow = value;
    }

    /**
     * Gets the value of the baseHigh property.
     *
     * @return
     *     possible object is
     *     {@link BaseHigh }
     *
     */
    public BaseHigh getBaseHigh() {
        return baseHigh;
    }

    /**
     * Sets the value of the baseHigh property.
     *
     * @param value
     *     allowed object is
     *     {@link BaseHigh }
     *
     */
    public void setBaseHigh(BaseHigh value) {
        this.baseHigh = value;
    }

    /**
     * Gets the value of the baseCenter property.
     *
     * @return
     *     possible object is
     *     {@link BaseCenter }
     *
     */
    public BaseCenter getBaseCenter() {
        return baseCenter;
    }

    /**
     * Sets the value of the baseCenter property.
     *
     * @param value
     *     allowed object is
     *     {@link BaseCenter }
     *
     */
    public void setBaseCenter(BaseCenter value) {
        this.baseCenter = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="center" type="{http://www.e-mis.com/emisopen}dt.DatePart"/&gt;
     *         &lt;element name="width" type="{http://www.e-mis.com/emisopen}dt.Duration" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "center",
        "width"
    })
    public static class BaseCenter {

        @XmlElement(required = true)
        protected DtDatePart center;
        protected DtDuration width;

        /**
         * Gets the value of the center property.
         * 
         * @return
         *     possible object is
         *     {@link DtDatePart }
         *     
         */
        public DtDatePart getCenter() {
            return center;
        }

        /**
         * Sets the value of the center property.
         * 
         * @param value
         *     allowed object is
         *     {@link DtDatePart }
         *     
         */
        public void setCenter(DtDatePart value) {
            this.center = value;
        }

        /**
         * Gets the value of the width property.
         * 
         * @return
         *     possible object is
         *     {@link DtDuration }
         *     
         */
        public DtDuration getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         * @param value
         *     allowed object is
         *     {@link DtDuration }
         *     
         */
        public void setWidth(DtDuration value) {
            this.width = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="high" type="{http://www.e-mis.com/emisopen}dt.DatePart"/&gt;
     *         &lt;choice minOccurs="0"&gt;
     *           &lt;element name="width" type="{http://www.e-mis.com/emisopen}dt.Duration" minOccurs="0"/&gt;
     *           &lt;element name="low" type="{http://www.e-mis.com/emisopen}dt.DatePart" minOccurs="0"/&gt;
     *         &lt;/choice&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "high",
        "width",
        "low"
    })
    public static class BaseHigh {

        @XmlElement(required = true)
        protected DtDatePart high;
        protected DtDuration width;
        protected DtDatePart low;

        /**
         * Gets the value of the high property.
         * 
         * @return
         *     possible object is
         *     {@link DtDatePart }
         *     
         */
        public DtDatePart getHigh() {
            return high;
        }

        /**
         * Sets the value of the high property.
         * 
         * @param value
         *     allowed object is
         *     {@link DtDatePart }
         *     
         */
        public void setHigh(DtDatePart value) {
            this.high = value;
        }

        /**
         * Gets the value of the width property.
         * 
         * @return
         *     possible object is
         *     {@link DtDuration }
         *     
         */
        public DtDuration getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         * @param value
         *     allowed object is
         *     {@link DtDuration }
         *     
         */
        public void setWidth(DtDuration value) {
            this.width = value;
        }

        /**
         * Gets the value of the low property.
         * 
         * @return
         *     possible object is
         *     {@link DtDatePart }
         *     
         */
        public DtDatePart getLow() {
            return low;
        }

        /**
         * Sets the value of the low property.
         * 
         * @param value
         *     allowed object is
         *     {@link DtDatePart }
         *     
         */
        public void setLow(DtDatePart value) {
            this.low = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="low" type="{http://www.e-mis.com/emisopen}dt.DatePart"/&gt;
     *         &lt;choice minOccurs="0"&gt;
     *           &lt;element name="width" type="{http://www.e-mis.com/emisopen}dt.Duration" minOccurs="0"/&gt;
     *           &lt;element name="high" type="{http://www.e-mis.com/emisopen}dt.DatePart" minOccurs="0"/&gt;
     *         &lt;/choice&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "low",
        "width",
        "high"
    })
    public static class BaseLow {

        @XmlElement(required = true)
        protected DtDatePart low;
        protected DtDuration width;
        protected DtDatePart high;

        /**
         * Gets the value of the low property.
         * 
         * @return
         *     possible object is
         *     {@link DtDatePart }
         *     
         */
        public DtDatePart getLow() {
            return low;
        }

        /**
         * Sets the value of the low property.
         * 
         * @param value
         *     allowed object is
         *     {@link DtDatePart }
         *     
         */
        public void setLow(DtDatePart value) {
            this.low = value;
        }

        /**
         * Gets the value of the width property.
         * 
         * @return
         *     possible object is
         *     {@link DtDuration }
         *     
         */
        public DtDuration getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         * @param value
         *     allowed object is
         *     {@link DtDuration }
         *     
         */
        public void setWidth(DtDuration value) {
            this.width = value;
        }

        /**
         * Gets the value of the high property.
         * 
         * @return
         *     possible object is
         *     {@link DtDatePart }
         *     
         */
        public DtDatePart getHigh() {
            return high;
        }

        /**
         * Sets the value of the high property.
         * 
         * @param value
         *     allowed object is
         *     {@link DtDatePart }
         *     
         */
        public void setHigh(DtDatePart value) {
            this.high = value;
        }

    }

}
