//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for EnquiryDocument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnquiryDocument"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.e-mis.com/emisopen}dt.uid"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="creationTime" type="{http://www.e-mis.com/emisopen}dt.DateTime"/&gt;
 *         &lt;element name="enquirer" type="{http://www.e-mis.com/emisopen}EQDOC.Enquirer" minOccurs="0"/&gt;
 *         &lt;element name="reportFolder" type="{http://www.e-mis.com/emisopen}EQDOC.Folder" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="report" type="{http://www.e-mis.com/emisopen}EQDOC.Report" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="libraryItem" type="{http://www.e-mis.com/emisopen}EQDOC.LibraryItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="mailMergeItem" type="{http://www.e-mis.com/emisopen}EQDOC.MailMerge" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="reportCollections" type="{http://www.e-mis.com/emisopen}EQDOC.ReportCollections" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="reportSetGroup" type="{http://www.e-mis.com/emisopen}EQDOC.ReportSetGroup" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="QMAS" type="{http://www.e-mis.com/emisopen}EQDOC.QMAS" minOccurs="0"/&gt;
 *         &lt;element name="GPES" type="{http://www.e-mis.com/emisopen}EQDOC.GPES" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="schemaVersion" use="required" type="{http://www.e-mis.com/emisopen}dt.Version" fixed="32.0.0" /&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.e-mis.com/emisopen}dt.Version" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnquiryDocument", propOrder = {
    "id",
    "name",
    "creationTime",
    "enquirer",
    "reportFolder",
    "report",
    "libraryItem",
    "mailMergeItem",
    "reportCollections",
    "reportSetGroup",
    "qmas",
    "gpes"
})
@XmlRootElement
public class EnquiryDocument {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String id;
    protected String name;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationTime;
    protected EQDOCEnquirer enquirer;
    protected List<EQDOCFolder> reportFolder;
    protected List<EQDOCReport> report;
    protected List<EQDOCLibraryItem> libraryItem;
    protected List<EQDOCMailMerge> mailMergeItem;
    protected List<EQDOCReportCollections> reportCollections;
    protected List<EQDOCReportSetGroup> reportSetGroup;
    @XmlElement(name = "QMAS")
    protected EQDOCQMAS qmas;
    @XmlElement(name = "GPES")
    protected EQDOCGPES gpes;
    @XmlAttribute(name = "schemaVersion", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String schemaVersion;
    @XmlAttribute(name = "version", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String version;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationTime(XMLGregorianCalendar value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the enquirer property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCEnquirer }
     *     
     */
    public EQDOCEnquirer getEnquirer() {
        return enquirer;
    }

    /**
     * Sets the value of the enquirer property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCEnquirer }
     *     
     */
    public void setEnquirer(EQDOCEnquirer value) {
        this.enquirer = value;
    }

    /**
     * Gets the value of the reportFolder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportFolder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportFolder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EQDOCFolder }
     * 
     * 
     */
    public List<EQDOCFolder> getReportFolder() {
        if (reportFolder == null) {
            reportFolder = new ArrayList<EQDOCFolder>();
        }
        return this.reportFolder;
    }

    /**
     * Gets the value of the report property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the report property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EQDOCReport }
     * 
     * 
     */
    public List<EQDOCReport> getReport() {
        if (report == null) {
            report = new ArrayList<EQDOCReport>();
        }
        return this.report;
    }

    /**
     * Gets the value of the libraryItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the libraryItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLibraryItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EQDOCLibraryItem }
     * 
     * 
     */
    public List<EQDOCLibraryItem> getLibraryItem() {
        if (libraryItem == null) {
            libraryItem = new ArrayList<EQDOCLibraryItem>();
        }
        return this.libraryItem;
    }

    /**
     * Gets the value of the mailMergeItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mailMergeItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMailMergeItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EQDOCMailMerge }
     * 
     * 
     */
    public List<EQDOCMailMerge> getMailMergeItem() {
        if (mailMergeItem == null) {
            mailMergeItem = new ArrayList<EQDOCMailMerge>();
        }
        return this.mailMergeItem;
    }

    /**
     * Gets the value of the reportCollections property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportCollections property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportCollections().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EQDOCReportCollections }
     * 
     * 
     */
    public List<EQDOCReportCollections> getReportCollections() {
        if (reportCollections == null) {
            reportCollections = new ArrayList<EQDOCReportCollections>();
        }
        return this.reportCollections;
    }

    /**
     * Gets the value of the reportSetGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportSetGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportSetGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EQDOCReportSetGroup }
     * 
     * 
     */
    public List<EQDOCReportSetGroup> getReportSetGroup() {
        if (reportSetGroup == null) {
            reportSetGroup = new ArrayList<EQDOCReportSetGroup>();
        }
        return this.reportSetGroup;
    }

    /**
     * Gets the value of the qmas property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCQMAS }
     *     
     */
    public EQDOCQMAS getQMAS() {
        return qmas;
    }

    /**
     * Sets the value of the qmas property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCQMAS }
     *     
     */
    public void setQMAS(EQDOCQMAS value) {
        this.qmas = value;
    }

    /**
     * Gets the value of the gpes property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCGPES }
     *     
     */
    public EQDOCGPES getGPES() {
        return gpes;
    }

    /**
     * Sets the value of the gpes property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCGPES }
     *     
     */
    public void setGPES(EQDOCGPES value) {
        this.gpes = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        if (schemaVersion == null) {
            return "32.0.0";
        } else {
            return schemaVersion;
        }
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
