//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for EQDOC.GPES complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.GPES"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="extractionRequirementGuid" type="{http://www.e-mis.com/emisopen}dt.uid"/&gt;
 *         &lt;element name="extractionRequirementVersion" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="queryIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="minimumCareRecordVersion" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="extractionRequirementSource" type="{http://www.e-mis.com/emisopen}voc.ExtractionRequirementSource"/&gt;
 *         &lt;element name="reportSetGroupGuid" type="{http://www.e-mis.com/emisopen}dt.uid"/&gt;
 *         &lt;element name="substitutionValues"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="substitutionValue" type="{http://www.e-mis.com/emisopen}EQDOC.GpesSubstitutionValue" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="output" type="{http://www.e-mis.com/emisopen}EQDOC.GpesOutput"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.GPES", propOrder = {
    "extractionRequirementGuid",
    "extractionRequirementVersion",
    "queryIdentifier",
    "minimumCareRecordVersion",
    "name",
    "extractionRequirementSource",
    "reportSetGroupGuid",
    "substitutionValues",
    "output"
})
public class EQDOCGPES {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String extractionRequirementGuid;
    @XmlElement(required = true)
    protected BigDecimal extractionRequirementVersion;
    @XmlElement(required = true)
    protected String queryIdentifier;
    protected int minimumCareRecordVersion;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected VocExtractionRequirementSource extractionRequirementSource;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String reportSetGroupGuid;
    @XmlElement(required = true)
    protected EQDOCGPES.SubstitutionValues substitutionValues;
    @XmlElement(required = true)
    protected EQDOCGpesOutput output;

    /**
     * Gets the value of the extractionRequirementGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtractionRequirementGuid() {
        return extractionRequirementGuid;
    }

    /**
     * Sets the value of the extractionRequirementGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtractionRequirementGuid(String value) {
        this.extractionRequirementGuid = value;
    }

    /**
     * Gets the value of the extractionRequirementVersion property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExtractionRequirementVersion() {
        return extractionRequirementVersion;
    }

    /**
     * Sets the value of the extractionRequirementVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExtractionRequirementVersion(BigDecimal value) {
        this.extractionRequirementVersion = value;
    }

    /**
     * Gets the value of the queryIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryIdentifier() {
        return queryIdentifier;
    }

    /**
     * Sets the value of the queryIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryIdentifier(String value) {
        this.queryIdentifier = value;
    }

    /**
     * Gets the value of the minimumCareRecordVersion property.
     * 
     */
    public int getMinimumCareRecordVersion() {
        return minimumCareRecordVersion;
    }

    /**
     * Sets the value of the minimumCareRecordVersion property.
     * 
     */
    public void setMinimumCareRecordVersion(int value) {
        this.minimumCareRecordVersion = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the extractionRequirementSource property.
     * 
     * @return
     *     possible object is
     *     {@link VocExtractionRequirementSource }
     *     
     */
    public VocExtractionRequirementSource getExtractionRequirementSource() {
        return extractionRequirementSource;
    }

    /**
     * Sets the value of the extractionRequirementSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocExtractionRequirementSource }
     *     
     */
    public void setExtractionRequirementSource(VocExtractionRequirementSource value) {
        this.extractionRequirementSource = value;
    }

    /**
     * Gets the value of the reportSetGroupGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportSetGroupGuid() {
        return reportSetGroupGuid;
    }

    /**
     * Sets the value of the reportSetGroupGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportSetGroupGuid(String value) {
        this.reportSetGroupGuid = value;
    }

    /**
     * Gets the value of the substitutionValues property.
     * 
     * @return
     *     possible object is
     *     {@link SubstitutionValues }
     *
     */
    public SubstitutionValues getSubstitutionValues() {
        return substitutionValues;
    }

    /**
     * Sets the value of the substitutionValues property.
     *
     * @param value
     *     allowed object is
     *     {@link SubstitutionValues }
     *
     */
    public void setSubstitutionValues(SubstitutionValues value) {
        this.substitutionValues = value;
    }

    /**
     * Gets the value of the output property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCGpesOutput }
     *     
     */
    public EQDOCGpesOutput getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCGpesOutput }
     *     
     */
    public void setOutput(EQDOCGpesOutput value) {
        this.output = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="substitutionValue" type="{http://www.e-mis.com/emisopen}EQDOC.GpesSubstitutionValue" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "substitutionValue"
    })
    public static class SubstitutionValues {

        @XmlElement(required = true)
        protected List<EQDOCGpesSubstitutionValue> substitutionValue;

        /**
         * Gets the value of the substitutionValue property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the substitutionValue property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSubstitutionValue().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EQDOCGpesSubstitutionValue }
         * 
         * 
         */
        public List<EQDOCGpesSubstitutionValue> getSubstitutionValue() {
            if (substitutionValue == null) {
                substitutionValue = new ArrayList<EQDOCGpesSubstitutionValue>();
            }
            return this.substitutionValue;
        }

    }

}
