//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for EQDOC.ListReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.ListReport"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="columnGroups" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="columnGroup" type="{http://www.e-mis.com/emisopen}EQDOC.ListColumnGroup"/&gt;
 *                   &lt;element name="libraryItem" type="{http://www.e-mis.com/emisopen}dt.uid"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="grouping" type="{http://www.e-mis.com/emisopen}EQDOC.ListGrouping" minOccurs="0"/&gt;
 *         &lt;element name="sort" type="{http://www.e-mis.com/emisopen}EQDOC.ListReportLevelSort" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.ListReport", propOrder = {
    "columnGroups",
    "grouping",
    "sort"
})
public class EQDOCListReport {

    @XmlElement(required = true)
    protected List<ColumnGroups> columnGroups;
    protected EQDOCListGrouping grouping;
    protected List<EQDOCListReportLevelSort> sort;

    /**
     * Gets the value of the columnGroups property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the columnGroups property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColumnGroups().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ColumnGroups }
     *
     *
     */
    public List<ColumnGroups> getColumnGroups() {
        if (columnGroups == null) {
            columnGroups = new ArrayList<ColumnGroups>();
        }
        return this.columnGroups;
    }

    /**
     * Gets the value of the grouping property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCListGrouping }
     *     
     */
    public EQDOCListGrouping getGrouping() {
        return grouping;
    }

    /**
     * Sets the value of the grouping property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCListGrouping }
     *     
     */
    public void setGrouping(EQDOCListGrouping value) {
        this.grouping = value;
    }

    /**
     * Gets the value of the sort property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sort property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSort().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EQDOCListReportLevelSort }
     * 
     * 
     */
    public List<EQDOCListReportLevelSort> getSort() {
        if (sort == null) {
            sort = new ArrayList<EQDOCListReportLevelSort>();
        }
        return this.sort;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="columnGroup" type="{http://www.e-mis.com/emisopen}EQDOC.ListColumnGroup"/&gt;
     *         &lt;element name="libraryItem" type="{http://www.e-mis.com/emisopen}dt.uid"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "columnGroup",
        "libraryItem"
    })
    public static class ColumnGroups {

        protected EQDOCListColumnGroup columnGroup;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String libraryItem;

        /**
         * Gets the value of the columnGroup property.
         * 
         * @return
         *     possible object is
         *     {@link EQDOCListColumnGroup }
         *     
         */
        public EQDOCListColumnGroup getColumnGroup() {
            return columnGroup;
        }

        /**
         * Sets the value of the columnGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link EQDOCListColumnGroup }
         *     
         */
        public void setColumnGroup(EQDOCListColumnGroup value) {
            this.columnGroup = value;
        }

        /**
         * Gets the value of the libraryItem property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLibraryItem() {
            return libraryItem;
        }

        /**
         * Sets the value of the libraryItem property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLibraryItem(String value) {
            this.libraryItem = value;
        }

    }

}
