//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EQDOC.GpesOutput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.GpesOutput"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GpesExtractionRequestConfiguration" type="{http://www.e-mis.com/emisopen}EQDOC.GpesExtractionRequestConfiguration"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.GpesOutput", propOrder = {
    "gpesExtractionRequestConfiguration"
})
public class EQDOCGpesOutput {

    @XmlElement(name = "GpesExtractionRequestConfiguration", required = true)
    protected EQDOCGpesExtractionRequestConfiguration gpesExtractionRequestConfiguration;

    /**
     * Gets the value of the gpesExtractionRequestConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCGpesExtractionRequestConfiguration }
     *     
     */
    public EQDOCGpesExtractionRequestConfiguration getGpesExtractionRequestConfiguration() {
        return gpesExtractionRequestConfiguration;
    }

    /**
     * Sets the value of the gpesExtractionRequestConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCGpesExtractionRequestConfiguration }
     *     
     */
    public void setGpesExtractionRequestConfiguration(EQDOCGpesExtractionRequestConfiguration value) {
        this.gpesExtractionRequestConfiguration = value;
    }

}
