//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for EQDOC.CriteriaGroupDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.CriteriaGroupDefinition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="memberOperator" type="{http://www.e-mis.com/emisopen}voc.MemberOperator"/&gt;
 *         &lt;element name="criteria" type="{http://www.e-mis.com/emisopen}EQDOC.Criteria" maxOccurs="unbounded"/&gt;
 *         &lt;element name="parentPopulationGuid" type="{http://www.e-mis.com/emisopen}dt.uid" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.CriteriaGroupDefinition", propOrder = {
    "memberOperator",
    "criteria",
    "parentPopulationGuid"
})
public class EQDOCCriteriaGroupDefinition {

    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected VocMemberOperator memberOperator;
    @XmlElement(required = true)
    protected List<EQDOCCriteria> criteria;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String parentPopulationGuid;

    /**
     * Gets the value of the memberOperator property.
     * 
     * @return
     *     possible object is
     *     {@link VocMemberOperator }
     *     
     */
    public VocMemberOperator getMemberOperator() {
        return memberOperator;
    }

    /**
     * Sets the value of the memberOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocMemberOperator }
     *     
     */
    public void setMemberOperator(VocMemberOperator value) {
        this.memberOperator = value;
    }

    /**
     * Gets the value of the criteria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the criteria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCriteria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EQDOCCriteria }
     * 
     * 
     */
    public List<EQDOCCriteria> getCriteria() {
        if (criteria == null) {
            criteria = new ArrayList<EQDOCCriteria>();
        }
        return this.criteria;
    }

    /**
     * Gets the value of the parentPopulationGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentPopulationGuid() {
        return parentPopulationGuid;
    }

    /**
     * Sets the value of the parentPopulationGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentPopulationGuid(String value) {
        this.parentPopulationGuid = value;
    }

}
