//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voc.AptStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="voc.AptStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="SA"/&gt;
 *     &lt;enumeration value="SB"/&gt;
 *     &lt;enumeration value="PA"/&gt;
 *     &lt;enumeration value="PSI"/&gt;
 *     &lt;enumeration value="PL"/&gt;
 *     &lt;enumeration value="DNA"/&gt;
 *     &lt;enumeration value="PWO"/&gt;
 *     &lt;enumeration value="VIS"/&gt;
 *     &lt;enumeration value="TC"/&gt;
 *     &lt;enumeration value="TNI"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "voc.AptStatus")
@XmlEnum
public enum VocAptStatus {


    /**
     * Slot Available
     * 
     */
    SA,

    /**
     * Slot Booked
     * 
     */
    SB,

    /**
     * Patient Arrived
     * 
     */
    PA,

    /**
     * Patient Sent In
     * 
     */
    PSI,

    /**
     * Patient Left
     * 
     */
    PL,

    /**
     * Patient DNA
     * 
     */
    DNA,

    /**
     * Patient Walked Out
     * 
     */
    PWO,

    /**
     * Visited
     * 
     */
    VIS,

    /**
     * Telephone - Complete
     * 
     */
    TC,

    /**
     * Telephone - Not In
     * 
     */
    TNI;

    public String value() {
        return name();
    }

    public static VocAptStatus fromValue(String v) {
        return valueOf(v);
    }

}
