//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voc.AssociatedTextType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="voc.AssociatedTextType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="RC"/&gt;
 *     &lt;enumeration value="FC"/&gt;
 *     &lt;enumeration value="PRE"/&gt;
 *     &lt;enumeration value="POST"/&gt;
 *     &lt;enumeration value="HEAD"/&gt;
 *     &lt;enumeration value="UC"/&gt;
 *     &lt;enumeration value="DI"/&gt;
 *     &lt;enumeration value="CI"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "voc.AssociatedTextType")
@XmlEnum
public enum VocAssociatedTextType {


    /**
     * Report comment
     * 
     */
    RC,

    /**
     * Filing comment
     * 
     */
    FC,

    /**
     * Pre clinical code text
     * 
     */
    PRE,

    /**
     * Post clinical code text
     * 
     */
    POST,

    /**
     * Heading
     * 
     */
    HEAD,

    /**
     * User Comment
     * 
     */
    UC,

    /**
     * Drug Information
     * 
     */
    DI,

    /**
     * Clinical Information
     * 
     */
    CI;

    public String value() {
        return name();
    }

    public static VocAssociatedTextType fromValue(String v) {
        return valueOf(v);
    }

}
