//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voc.BandingHierarchyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="voc.BandingHierarchyType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="drugChapter"/&gt;
 *     &lt;enumeration value="readCode"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "voc.BandingHierarchyType")
@XmlEnum
public enum VocBandingHierarchyType {

    @XmlEnumValue("drugChapter")
    DRUG_CHAPTER("drugChapter"),
    @XmlEnumValue("readCode")
    READ_CODE("readCode");
    private final String value;

    VocBandingHierarchyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VocBandingHierarchyType fromValue(String v) {
        for (VocBandingHierarchyType c: VocBandingHierarchyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
