//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voc.BandDateTimeUnit.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="voc.BandDateTimeUnit"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="DATETIME"/&gt;
 *     &lt;enumeration value="DATE"/&gt;
 *     &lt;enumeration value="DAY"/&gt;
 *     &lt;enumeration value="WEEK"/&gt;
 *     &lt;enumeration value="YEAR"/&gt;
 *     &lt;enumeration value="MONTH"/&gt;
 *     &lt;enumeration value="WEEKOFYEAR"/&gt;
 *     &lt;enumeration value="DAYOFWEEK"/&gt;
 *     &lt;enumeration value="HOUR"/&gt;
 *     &lt;enumeration value="MINUTE"/&gt;
 *     &lt;enumeration value="HOURMINUTE"/&gt;
 *     &lt;enumeration value="QUARTER"/&gt;
 *     &lt;enumeration value="FISCALYEAR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "voc.BandDateTimeUnit")
@XmlEnum
public enum VocBandDateTimeUnit {


    /**
     * Specific date + time (e.g. "1971-11-19 15:35")
     * 
     */
    DATETIME,

    /**
     * Specific date (e.g. 1971-11-19)
     * 
     */
    DATE,

    /**
     * Represents numeric number of days
     * 
     */
    DAY,

    /**
     * Represents numeric number of weeks
     * 
     */
    WEEK,

    /**
     * Year
     * 
     */
    YEAR,

    /**
     * Numeric month.  1=Jan, 12=Dec
     * 
     */
    MONTH,

    /**
     * Numeric week. When is week 1???
     * 
     */
    WEEKOFYEAR,

    /**
     * MON, TUE, WED, THU, FRI, SAT, SUN
     * 
     */
    DAYOFWEEK,

    /**
     *  1-24
     * 
     */
    HOUR,

    /**
     *  1-60
     * 
     */
    MINUTE,

    /**
     * Eg 15:30
     * 
     */
    HOURMINUTE,
    QUARTER,
    FISCALYEAR;

    public String value() {
        return name();
    }

    public static VocBandDateTimeUnit fromValue(String v) {
        return valueOf(v);
    }

}
