//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voc.Episodicity.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="voc.Episodicity"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="NONE"/&gt;
 *     &lt;enumeration value="FIRST"/&gt;
 *     &lt;enumeration value="NEW"/&gt;
 *     &lt;enumeration value="REV"/&gt;
 *     &lt;enumeration value="FLA"/&gt;
 *     &lt;enumeration value="END"/&gt;
 *     &lt;enumeration value="CHG"/&gt;
 *     &lt;enumeration value="EVO"/&gt;
 *     &lt;enumeration value="OUT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "voc.Episodicity")
@XmlEnum
public enum VocEpisodicity {


    /**
     * None
     * 
     */
    NONE,

    /**
     * First Occurrence
     * 
     */
    FIRST,

    /**
     * New Occurrence
     * 
     */
    NEW,

    /**
     * Problem Review
     * 
     */
    REV,

    /**
     * Problem Flare Up
     * 
     */
    FLA,

    /**
     * Problem Ended
     * 
     */
    END,

    /**
     * Changed
     * 
     */
    CHG,

    /**
     * Evolved
     * 
     */
    EVO,

    /**
     * Problem Outcome
     * 
     */
    OUT;

    public String value() {
        return name();
    }

    public static VocEpisodicity fromValue(String v) {
        return valueOf(v);
    }

}
