//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voc.PatientIdentifierType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="voc.PatientIdentifierType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="NHS"/&gt;
 *     &lt;enumeration value="ONHS"/&gt;
 *     &lt;enumeration value="CHI"/&gt;
 *     &lt;enumeration value="HC"/&gt;
 *     &lt;enumeration value="GRO"/&gt;
 *     &lt;enumeration value="UPCI"/&gt;
 *     &lt;enumeration value="MOD"/&gt;
 *     &lt;enumeration value="SSH"/&gt;
 *     &lt;enumeration value="INS"/&gt;
 *     &lt;enumeration value="ARMY"/&gt;
 *     &lt;enumeration value="RAF"/&gt;
 *     &lt;enumeration value="NAVY"/&gt;
 *     &lt;enumeration value="HOSP"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "voc.PatientIdentifierType")
@XmlEnum
public enum VocPatientIdentifierType {


    /**
     * NHS Number
     * 
     */
    NHS,

    /**
     * Old NHS Number
     * 
     */
    ONHS,

    /**
     * CHI Number
     * 
     */
    CHI,

    /**
     * HC Number
     * 
     */
    HC,

    /**
     * GRO Number
     * 
     */
    GRO,

    /**
     * UPCI Number
     * 
     */
    UPCI,

    /**
     * MOD Service Number
     * 
     */
    MOD,

    /**
     * SSH Number
     * 
     */
    SSH,

    /**
     * Insurance Number
     * 
     */
    INS,

    /**
     * Army Number
     * 
     */
    ARMY,

    /**
     * Royal Air Force Number
     * 
     */
    RAF,

    /**
     * Royal Navy Number
     * 
     */
    NAVY,

    /**
     * Hospital Number
     * 
     */
    HOSP;

    public String value() {
        return name();
    }

    public static VocPatientIdentifierType fromValue(String v) {
        return valueOf(v);
    }

}
