//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voc.ReferralRequestType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="voc.ReferralRequestType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="UNK"/&gt;
 *     &lt;enumeration value="OUT"/&gt;
 *     &lt;enumeration value="ADM"/&gt;
 *     &lt;enumeration value="DAY"/&gt;
 *     &lt;enumeration value="INV"/&gt;
 *     &lt;enumeration value="DOM"/&gt;
 *     &lt;enumeration value="SELF"/&gt;
 *     &lt;enumeration value="COM"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "voc.ReferralRequestType")
@XmlEnum
public enum VocReferralRequestType {


    /**
     * Unknown
     * 
     */
    UNK,

    /**
     * Outpatient
     * 
     */
    OUT,

    /**
     * Admission
     * 
     */
    ADM,

    /**
     * Day care
     * 
     */
    DAY,

    /**
     * Investigation
     * 
     */
    INV,

    /**
     * Domiciliary visit
     * 
     */
    DOM,

    /**
     * Self referral
     * 
     */
    SELF,

    /**
     * Community Care
     * 
     */
    COM;

    public String value() {
        return name();
    }

    public static VocReferralRequestType fromValue(String v) {
        return valueOf(v);
    }

}
