//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voc.SearchDateType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="voc.SearchDateType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="BASELINE"/&gt;
 *     &lt;enumeration value="REFERENCE"/&gt;
 *     &lt;enumeration value="TODAY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "voc.SearchDateType")
@XmlEnum
public enum VocSearchDateType {


    /**
     * Baseline date
     * 
     */
    BASELINE,

    /**
     * Reference date
     * 
     */
    REFERENCE,

    /**
     * Todays date
     * 
     */
    TODAY;

    public String value() {
        return name();
    }

    public static VocSearchDateType fromValue(String v) {
        return valueOf(v);
    }

}
