//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.sources.eqd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voc.TaskType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="voc.TaskType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="BOOK_APPOINTMENT"/&gt;
 *     &lt;enumeration value="BOOK_APPOINTMENT_DOCTOR"/&gt;
 *     &lt;enumeration value="BOOK_APPOINTMENT_NURSE"/&gt;
 *     &lt;enumeration value="TELEPHONE_PATIENT"/&gt;
 *     &lt;enumeration value="SCREEN_MESSAGE"/&gt;
 *     &lt;enumeration value="RESULTS_FOR_INFO"/&gt;
 *     &lt;enumeration value="MEETING_NOTIFICATION"/&gt;
 *     &lt;enumeration value="PATIENT_NOTE"/&gt;
 *     &lt;enumeration value="ADMIN_NOTE"/&gt;
 *     &lt;enumeration value="FORM_TO_COMPLETE"/&gt;
 *     &lt;enumeration value="REPEAT_TEST"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "voc.TaskType")
@XmlEnum
public enum VocTaskType {

    BOOK_APPOINTMENT,
    BOOK_APPOINTMENT_DOCTOR,
    BOOK_APPOINTMENT_NURSE,
    TELEPHONE_PATIENT,
    SCREEN_MESSAGE,
    RESULTS_FOR_INFO,
    MEETING_NOTIFICATION,
    PATIENT_NOTE,
    ADMIN_NOTE,
    FORM_TO_COMPLETE,
    REPEAT_TEST;

    public String value() {
        return name();
    }

    public static VocTaskType fromValue(String v) {
        return valueOf(v);
    }

}
