//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Represents a specific instant of time (ISO 8601). Combinations of date and time of day values are defined by the datepart property.
 * 
 * <p>Java class for dt.DatePart complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dt.DatePart"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="datepart" use="required" type="{http://www.e-mis.com/emisopen}voc.DatePart" /&gt;
 *       &lt;attribute name="value" type="{http://www.e-mis.com/emisopen}dt.DateTime" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dt.DatePart")
public class DtDatePart {

    @XmlAttribute(name = "datepart", required = true)
    protected VocDatePart datepart;
    @XmlAttribute(name = "value")
    protected XMLGregorianCalendar value;

    /**
     * Gets the value of the datepart property.
     * 
     * @return
     *     possible object is
     *     {@link VocDatePart }
     *     
     */
    public VocDatePart getDatepart() {
        return datepart;
    }

    /**
     * Sets the value of the datepart property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocDatePart }
     *     
     */
    public void setDatepart(VocDatePart value) {
        this.datepart = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValue(XMLGregorianCalendar value) {
        this.value = value;
    }

}
