//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EQDOC.RecordFrequency complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.RecordFrequency"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="frequencyValue" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="frequencyRange" type="{http://www.e-mis.com/emisopen}EQDOC.FrequencyRange"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.RecordFrequency", propOrder = {
    "frequencyValue",
    "frequencyRange"
})
public class EQDOCRecordFrequency {

    protected Integer frequencyValue;
    protected EQDOCFrequencyRange frequencyRange;

    /**
     * Gets the value of the frequencyValue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFrequencyValue() {
        return frequencyValue;
    }

    /**
     * Sets the value of the frequencyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFrequencyValue(Integer value) {
        this.frequencyValue = value;
    }

    /**
     * Gets the value of the frequencyRange property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCFrequencyRange }
     *     
     */
    public EQDOCFrequencyRange getFrequencyRange() {
        return frequencyRange;
    }

    /**
     * Sets the value of the frequencyRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCFrequencyRange }
     *     
     */
    public void setFrequencyRange(EQDOCFrequencyRange value) {
        this.frequencyRange = value;
    }

}
