//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EQDOC.LinkedCriterion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.LinkedCriterion"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="relationship" type="{http://www.e-mis.com/emisopen}EQDOC.Relationship"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="criterion" type="{http://www.e-mis.com/emisopen}EQDOC.Criterion"/&gt;
 *           &lt;element name="libraryItem" type="{http://www.e-mis.com/emisopen}EQDOC.LibraryItemCriterion"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.LinkedCriterion", propOrder = {
    "relationship",
    "criterion",
    "libraryItem"
})
public class EQDOCLinkedCriterion {

    @XmlElement(required = true)
    protected EQDOCRelationship relationship;
    protected EQDOCCriterion criterion;
    protected EQDOCLibraryItemCriterion libraryItem;

    /**
     * Gets the value of the relationship property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCRelationship }
     *     
     */
    public EQDOCRelationship getRelationship() {
        return relationship;
    }

    /**
     * Sets the value of the relationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCRelationship }
     *     
     */
    public void setRelationship(EQDOCRelationship value) {
        this.relationship = value;
    }

    /**
     * Gets the value of the criterion property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCCriterion }
     *     
     */
    public EQDOCCriterion getCriterion() {
        return criterion;
    }

    /**
     * Sets the value of the criterion property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCCriterion }
     *     
     */
    public void setCriterion(EQDOCCriterion value) {
        this.criterion = value;
    }

    /**
     * Gets the value of the libraryItem property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCLibraryItemCriterion }
     *     
     */
    public EQDOCLibraryItemCriterion getLibraryItem() {
        return libraryItem;
    }

    /**
     * Sets the value of the libraryItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCLibraryItemCriterion }
     *     
     */
    public void setLibraryItem(EQDOCLibraryItemCriterion value) {
        this.libraryItem = value;
    }

}
