//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Defines the version independent GUID of a pop man search
 * 
 * <p>Java class for EQDOC.SearchIdentifier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.SearchIdentifier"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="reportGuid" type="{http://www.e-mis.com/emisopen}dt.uid" /&gt;
 *       &lt;attribute name="versionIndependentGuid" type="{http://www.e-mis.com/emisopen}dt.uid" /&gt;
 *       &lt;attribute name="populationType" type="{http://www.e-mis.com/emisopen}voc.InstanceType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.SearchIdentifier")
public class EQDOCSearchIdentifier {

    @XmlAttribute(name = "reportGuid")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String reportGuid;
    @XmlAttribute(name = "versionIndependentGuid")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String versionIndependentGuid;
    @XmlAttribute(name = "populationType")
    protected VocInstanceType populationType;

    /**
     * Gets the value of the reportGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportGuid() {
        return reportGuid;
    }

    /**
     * Sets the value of the reportGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportGuid(String value) {
        this.reportGuid = value;
    }

    /**
     * Gets the value of the versionIndependentGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionIndependentGuid() {
        return versionIndependentGuid;
    }

    /**
     * Sets the value of the versionIndependentGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionIndependentGuid(String value) {
        this.versionIndependentGuid = value;
    }

    /**
     * Gets the value of the populationType property.
     * 
     * @return
     *     possible object is
     *     {@link VocInstanceType }
     *     
     */
    public VocInstanceType getPopulationType() {
        return populationType;
    }

    /**
     * Sets the value of the populationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocInstanceType }
     *     
     */
    public void setPopulationType(VocInstanceType value) {
        this.populationType = value;
    }

}
