//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for EQDOC.SchedulePatternMonthly complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.SchedulePatternMonthly"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="dayOfMonth"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="dayOfMonth"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *                         &lt;minInclusive value="1"/&gt;
 *                         &lt;maxInclusive value="31"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="interval" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="dayOfWeek"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="occurrence" type="{http://www.e-mis.com/emisopen}voc.SchedulePatternOccurrence"/&gt;
 *                   &lt;element name="dayOfWeek" type="{http://www.e-mis.com/emisopen}voc.DayOfWeek"/&gt;
 *                   &lt;element name="interval" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.SchedulePatternMonthly", propOrder = {
    "dayOfMonth",
    "dayOfWeek"
})
public class EQDOCSchedulePatternMonthly {

    protected EQDOCSchedulePatternMonthly.DayOfMonth dayOfMonth;
    protected EQDOCSchedulePatternMonthly.DayOfWeek dayOfWeek;

    /**
     * Gets the value of the dayOfMonth property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCSchedulePatternMonthly.DayOfMonth }
     *     
     */
    public EQDOCSchedulePatternMonthly.DayOfMonth getDayOfMonth() {
        return dayOfMonth;
    }

    /**
     * Sets the value of the dayOfMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCSchedulePatternMonthly.DayOfMonth }
     *     
     */
    public void setDayOfMonth(EQDOCSchedulePatternMonthly.DayOfMonth value) {
        this.dayOfMonth = value;
    }

    /**
     * Gets the value of the dayOfWeek property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCSchedulePatternMonthly.DayOfWeek }
     *     
     */
    public EQDOCSchedulePatternMonthly.DayOfWeek getDayOfWeek() {
        return dayOfWeek;
    }

    /**
     * Sets the value of the dayOfWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCSchedulePatternMonthly.DayOfWeek }
     *     
     */
    public void setDayOfWeek(EQDOCSchedulePatternMonthly.DayOfWeek value) {
        this.dayOfWeek = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="dayOfMonth"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
     *               &lt;minInclusive value="1"/&gt;
     *               &lt;maxInclusive value="31"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="interval" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dayOfMonth",
        "interval"
    })
    public static class DayOfMonth {

        protected int dayOfMonth;
        protected int interval;

        /**
         * Gets the value of the dayOfMonth property.
         * 
         */
        public int getDayOfMonth() {
            return dayOfMonth;
        }

        /**
         * Sets the value of the dayOfMonth property.
         * 
         */
        public void setDayOfMonth(int value) {
            this.dayOfMonth = value;
        }

        /**
         * Gets the value of the interval property.
         * 
         */
        public int getInterval() {
            return interval;
        }

        /**
         * Sets the value of the interval property.
         * 
         */
        public void setInterval(int value) {
            this.interval = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="occurrence" type="{http://www.e-mis.com/emisopen}voc.SchedulePatternOccurrence"/&gt;
     *         &lt;element name="dayOfWeek" type="{http://www.e-mis.com/emisopen}voc.DayOfWeek"/&gt;
     *         &lt;element name="interval" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "occurrence",
        "dayOfWeek",
        "interval"
    })
    public static class DayOfWeek {

        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String occurrence;
        @XmlElement(required = true)
        @XmlSchemaType(name = "token")
        protected VocDayOfWeek dayOfWeek;
        protected int interval;

        /**
         * Gets the value of the occurrence property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOccurrence() {
            return occurrence;
        }

        /**
         * Sets the value of the occurrence property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOccurrence(String value) {
            this.occurrence = value;
        }

        /**
         * Gets the value of the dayOfWeek property.
         * 
         * @return
         *     possible object is
         *     {@link VocDayOfWeek }
         *     
         */
        public VocDayOfWeek getDayOfWeek() {
            return dayOfWeek;
        }

        /**
         * Sets the value of the dayOfWeek property.
         * 
         * @param value
         *     allowed object is
         *     {@link VocDayOfWeek }
         *     
         */
        public void setDayOfWeek(VocDayOfWeek value) {
            this.dayOfWeek = value;
        }

        /**
         * Gets the value of the interval property.
         * 
         */
        public int getInterval() {
            return interval;
        }

        /**
         * Sets the value of the interval property.
         * 
         */
        public void setInterval(int value) {
            this.interval = value;
        }

    }

}
