//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EQDOC.RangeTo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.RangeTo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="operator" type="{http://www.e-mis.com/emisopen}voc.RangeToOperator" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element name="value" type="{http://www.e-mis.com/emisopen}EQDOC.Value"/&gt;
 *           &lt;element name="function" type="{http://www.e-mis.com/emisopen}EQDOC.MethodCall"/&gt;
 *           &lt;element name="substitutionIdentifier" type="{http://www.e-mis.com/emisopen}EQDOC.SubstitutionIdentifier"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.RangeTo", propOrder = {
    "operator",
    "value",
    "function",
    "substitutionIdentifier"
})
public class EQDOCRangeTo {

    @XmlSchemaType(name = "token")
    protected VocRangeToOperator operator;
    protected EQDOCValue value;
    protected EQDOCMethodCall function;
    protected EQDOCSubstitutionIdentifier substitutionIdentifier;

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link VocRangeToOperator }
     *     
     */
    public VocRangeToOperator getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocRangeToOperator }
     *     
     */
    public void setOperator(VocRangeToOperator value) {
        this.operator = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCValue }
     *     
     */
    public EQDOCValue getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCValue }
     *     
     */
    public void setValue(EQDOCValue value) {
        this.value = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCMethodCall }
     *     
     */
    public EQDOCMethodCall getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCMethodCall }
     *     
     */
    public void setFunction(EQDOCMethodCall value) {
        this.function = value;
    }

    /**
     * Gets the value of the substitutionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCSubstitutionIdentifier }
     *     
     */
    public EQDOCSubstitutionIdentifier getSubstitutionIdentifier() {
        return substitutionIdentifier;
    }

    /**
     * Sets the value of the substitutionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCSubstitutionIdentifier }
     *     
     */
    public void setSubstitutionIdentifier(EQDOCSubstitutionIdentifier value) {
        this.substitutionIdentifier = value;
    }

}
