//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EQDOC.PopulationParent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.PopulationParent"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SearchIdentifier" type="{http://www.e-mis.com/emisopen}EQDOC.SearchIdentifier" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="parentType" use="required" type="{http://www.e-mis.com/emisopen}voc.PopulationParentType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.PopulationParent", propOrder = {
    "searchIdentifier"
})
public class EQDOCPopulationParent {

    @XmlElement(name = "SearchIdentifier")
    protected EQDOCSearchIdentifier searchIdentifier;
    @XmlAttribute(name = "parentType", required = true)
    protected VocPopulationParentType parentType;

    /**
     * Gets the value of the searchIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCSearchIdentifier }
     *     
     */
    public EQDOCSearchIdentifier getSearchIdentifier() {
        return searchIdentifier;
    }

    /**
     * Sets the value of the searchIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCSearchIdentifier }
     *     
     */
    public void setSearchIdentifier(EQDOCSearchIdentifier value) {
        this.searchIdentifier = value;
    }

    /**
     * Gets the value of the parentType property.
     * 
     * @return
     *     possible object is
     *     {@link VocPopulationParentType }
     *     
     */
    public VocPopulationParentType getParentType() {
        return parentType;
    }

    /**
     * Sets the value of the parentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocPopulationParentType }
     *     
     */
    public void setParentType(VocPopulationParentType value) {
        this.parentType = value;
    }

}
