//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for EQDOC.GpesPatientLevelTableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.GpesPatientLevelTableType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="fieldFromColumn" type="{http://www.e-mis.com/emisopen}EQDOC.GpesFieldFromColumnType"/&gt;
 *         &lt;element name="fixedValue" type="{http://www.e-mis.com/emisopen}EQDOC.GpesFieldFixedValueType"/&gt;
 *         &lt;element name="primaryKey" type="{http://www.e-mis.com/emisopen}EQDOC.GpesFieldPrimaryKeyType"/&gt;
 *         &lt;element name="link" type="{http://www.e-mis.com/emisopen}EQDOC.GpesFieldLinkType"/&gt;
 *         &lt;element name="fieldFromPatientLookup" type="{http://www.e-mis.com/emisopen}EQDOC.GpesFieldFromPatientLookup"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="columnGroupGuid" use="required" type="{http://www.e-mis.com/emisopen}dt.uid" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.GpesPatientLevelTableType", propOrder = {
    "fieldFromColumnOrFixedValueOrPrimaryKey"
})
public class EQDOCGpesPatientLevelTableType {

    @XmlElements({
        @XmlElement(name = "fieldFromColumn", type = EQDOCGpesFieldFromColumnType.class),
        @XmlElement(name = "fixedValue", type = EQDOCGpesFieldFixedValueType.class),
        @XmlElement(name = "primaryKey", type = EQDOCGpesFieldPrimaryKeyType.class),
        @XmlElement(name = "link", type = EQDOCGpesFieldLinkType.class),
        @XmlElement(name = "fieldFromPatientLookup", type = EQDOCGpesFieldFromPatientLookup.class)
    })
    protected List<Object> fieldFromColumnOrFixedValueOrPrimaryKey;
    @XmlAttribute(name = "columnGroupGuid", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String columnGroupGuid;

    /**
     * Gets the value of the fieldFromColumnOrFixedValueOrPrimaryKey property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldFromColumnOrFixedValueOrPrimaryKey property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldFromColumnOrFixedValueOrPrimaryKey().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EQDOCGpesFieldFromColumnType }
     * {@link EQDOCGpesFieldFixedValueType }
     * {@link EQDOCGpesFieldPrimaryKeyType }
     * {@link EQDOCGpesFieldLinkType }
     * {@link EQDOCGpesFieldFromPatientLookup }
     * 
     * 
     */
    public List<Object> getFieldFromColumnOrFixedValueOrPrimaryKey() {
        if (fieldFromColumnOrFixedValueOrPrimaryKey == null) {
            fieldFromColumnOrFixedValueOrPrimaryKey = new ArrayList<Object>();
        }
        return this.fieldFromColumnOrFixedValueOrPrimaryKey;
    }

    /**
     * Gets the value of the columnGroupGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnGroupGuid() {
        return columnGroupGuid;
    }

    /**
     * Sets the value of the columnGroupGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnGroupGuid(String value) {
        this.columnGroupGuid = value;
    }

}
