//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for EQDOC.PatientFilter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.PatientFilter"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="excludePDSSensitivePatients" type="{http://www.e-mis.com/emisopen}EQDOC.ExcludePDSSensitivePatientsFlagType" minOccurs="0"/&gt;
 *         &lt;element name="excludeDCRPatients" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="patientGuid" type="{http://www.e-mis.com/emisopen}dt.uid" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.PatientFilter", propOrder = {
    "excludePDSSensitivePatients",
    "excludeDCRPatients"
})
public class EQDOCPatientFilter {

    protected EQDOCExcludePDSSensitivePatientsFlagType excludePDSSensitivePatients;
    protected EQDOCPatientFilter.ExcludeDCRPatients excludeDCRPatients;

    /**
     * Gets the value of the excludePDSSensitivePatients property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCExcludePDSSensitivePatientsFlagType }
     *     
     */
    public EQDOCExcludePDSSensitivePatientsFlagType getExcludePDSSensitivePatients() {
        return excludePDSSensitivePatients;
    }

    /**
     * Sets the value of the excludePDSSensitivePatients property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCExcludePDSSensitivePatientsFlagType }
     *     
     */
    public void setExcludePDSSensitivePatients(EQDOCExcludePDSSensitivePatientsFlagType value) {
        this.excludePDSSensitivePatients = value;
    }

    /**
     * Gets the value of the excludeDCRPatients property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCPatientFilter.ExcludeDCRPatients }
     *     
     */
    public EQDOCPatientFilter.ExcludeDCRPatients getExcludeDCRPatients() {
        return excludeDCRPatients;
    }

    /**
     * Sets the value of the excludeDCRPatients property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCPatientFilter.ExcludeDCRPatients }
     *     
     */
    public void setExcludeDCRPatients(EQDOCPatientFilter.ExcludeDCRPatients value) {
        this.excludeDCRPatients = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="patientGuid" type="{http://www.e-mis.com/emisopen}dt.uid" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "patientGuid"
    })
    public static class ExcludeDCRPatients {

        @XmlElement(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected List<String> patientGuid;

        /**
         * Gets the value of the patientGuid property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the patientGuid property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPatientGuid().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPatientGuid() {
            if (patientGuid == null) {
                patientGuid = new ArrayList<String>();
            }
            return this.patientGuid;
        }

    }

}
