//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EQDOC.MailMergeTable complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.MailMergeTable"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="logicalTableName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="columns" type="{http://www.e-mis.com/emisopen}EQDOC.ListColumn" maxOccurs="unbounded"/&gt;
 *         &lt;element name="sort" type="{http://www.e-mis.com/emisopen}EQDOC.ListSortColumn" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="criteria" type="{http://www.e-mis.com/emisopen}EQDOC.Criteria" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.MailMergeTable", propOrder = {
    "logicalTableName",
    "columns",
    "sort",
    "criteria"
})
public class EQDOCMailMergeTable {

    @XmlElement(required = true)
    protected String logicalTableName;
    @XmlElement(required = true)
    protected List<EQDOCListColumn> columns;
    protected List<EQDOCListSortColumn> sort;
    protected EQDOCCriteria criteria;

    /**
     * Gets the value of the logicalTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogicalTableName() {
        return logicalTableName;
    }

    /**
     * Sets the value of the logicalTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogicalTableName(String value) {
        this.logicalTableName = value;
    }

    /**
     * Gets the value of the columns property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the columns property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColumns().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EQDOCListColumn }
     * 
     * 
     */
    public List<EQDOCListColumn> getColumns() {
        if (columns == null) {
            columns = new ArrayList<EQDOCListColumn>();
        }
        return this.columns;
    }

    /**
     * Gets the value of the sort property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sort property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSort().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EQDOCListSortColumn }
     * 
     * 
     */
    public List<EQDOCListSortColumn> getSort() {
        if (sort == null) {
            sort = new ArrayList<EQDOCListSortColumn>();
        }
        return this.sort;
    }

    /**
     * Gets the value of the criteria property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCCriteria }
     *     
     */
    public EQDOCCriteria getCriteria() {
        return criteria;
    }

    /**
     * Sets the value of the criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCCriteria }
     *     
     */
    public void setCriteria(EQDOCCriteria value) {
        this.criteria = value;
    }

}
