//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EQDOC.SingleValue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.SingleValue"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="constant" type="{http://www.e-mis.com/emisopen}voc.SingleValueConstant"/&gt;
 *         &lt;element name="variable" type="{http://www.e-mis.com/emisopen}EQDOC.Value"/&gt;
 *         &lt;element name="function" type="{http://www.e-mis.com/emisopen}EQDOC.MethodCall"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.SingleValue", propOrder = {
    "constant",
    "variable",
    "function"
})
public class EQDOCSingleValue {

    @XmlSchemaType(name = "token")
    protected VocSingleValueConstant constant;
    protected EQDOCValue variable;
    protected EQDOCMethodCall function;

    /**
     * Gets the value of the constant property.
     * 
     * @return
     *     possible object is
     *     {@link VocSingleValueConstant }
     *     
     */
    public VocSingleValueConstant getConstant() {
        return constant;
    }

    /**
     * Sets the value of the constant property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocSingleValueConstant }
     *     
     */
    public void setConstant(VocSingleValueConstant value) {
        this.constant = value;
    }

    /**
     * Gets the value of the variable property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCValue }
     *     
     */
    public EQDOCValue getVariable() {
        return variable;
    }

    /**
     * Sets the value of the variable property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCValue }
     *     
     */
    public void setVariable(EQDOCValue value) {
        this.variable = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link EQDOCMethodCall }
     *     
     */
    public EQDOCMethodCall getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link EQDOCMethodCall }
     *     
     */
    public void setFunction(EQDOCMethodCall value) {
        this.function = value;
    }

}
