//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EQDOC.AggregateResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EQDOC.AggregateResult"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="source" type="{http://www.e-mis.com/emisopen}voc.AggregateSource"/&gt;
 *         &lt;element name="column" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="calculationType" type="{http://www.e-mis.com/emisopen}voc.CalculationType"/&gt;
 *         &lt;element name="displayUnit" type="{http://www.e-mis.com/emisopen}voc.DisplayStyle" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EQDOC.AggregateResult", propOrder = {
    "source",
    "column",
    "calculationType",
    "displayUnit"
})
public class EQDOCAggregateResult {

    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected VocAggregateSource source;
    protected String column;
    @XmlElement(required = true)
    @XmlSchemaType(name = "token")
    protected VocCalculationType calculationType;
    @XmlSchemaType(name = "token")
    protected VocDisplayStyle displayUnit;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link VocAggregateSource }
     *     
     */
    public VocAggregateSource getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocAggregateSource }
     *     
     */
    public void setSource(VocAggregateSource value) {
        this.source = value;
    }

    /**
     * Gets the value of the column property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumn() {
        return column;
    }

    /**
     * Sets the value of the column property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumn(String value) {
        this.column = value;
    }

    /**
     * Gets the value of the calculationType property.
     * 
     * @return
     *     possible object is
     *     {@link VocCalculationType }
     *     
     */
    public VocCalculationType getCalculationType() {
        return calculationType;
    }

    /**
     * Sets the value of the calculationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocCalculationType }
     *     
     */
    public void setCalculationType(VocCalculationType value) {
        this.calculationType = value;
    }

    /**
     * Gets the value of the displayUnit property.
     * 
     * @return
     *     possible object is
     *     {@link VocDisplayStyle }
     *     
     */
    public VocDisplayStyle getDisplayUnit() {
        return displayUnit;
    }

    /**
     * Sets the value of the displayUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link VocDisplayStyle }
     *     
     */
    public void setDisplayUnit(VocDisplayStyle value) {
        this.displayUnit = value;
    }

}
