//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voc.DisplayStyle.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="voc.DisplayStyle"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="DURATION_MINUTES"/&gt;
 *     &lt;enumeration value="DURATION_HOURS"/&gt;
 *     &lt;enumeration value="DURATION_DAYS"/&gt;
 *     &lt;enumeration value="DURATION_WEEKS"/&gt;
 *     &lt;enumeration value="DURATION_MONTHS"/&gt;
 *     &lt;enumeration value="DURATION_YEARS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "voc.DisplayStyle")
@XmlEnum
public enum VocDisplayStyle {

    DURATION_MINUTES,
    DURATION_HOURS,
    DURATION_DAYS,
    DURATION_WEEKS,
    DURATION_MONTHS,
    DURATION_YEARS;

    public String value() {
        return name();
    }

    public static VocDisplayStyle fromValue(String v) {
        return valueOf(v);
    }

}
