//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voc.EncounterHeading.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="voc.EncounterHeading"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="ADD"/&gt;
 *     &lt;enumeration value="PROB"/&gt;
 *     &lt;enumeration value="HIST"/&gt;
 *     &lt;enumeration value="EXAM"/&gt;
 *     &lt;enumeration value="FH"/&gt;
 *     &lt;enumeration value="SOC"/&gt;
 *     &lt;enumeration value="COM"/&gt;
 *     &lt;enumeration value="RES"/&gt;
 *     &lt;enumeration value="MED"/&gt;
 *     &lt;enumeration value="DRY"/&gt;
 *     &lt;enumeration value="TR"/&gt;
 *     &lt;enumeration value="REF"/&gt;
 *     &lt;enumeration value="ALL"/&gt;
 *     &lt;enumeration value="RA"/&gt;
 *     &lt;enumeration value="SS"/&gt;
 *     &lt;enumeration value="PR"/&gt;
 *     &lt;enumeration value="HTGC"/&gt;
 *     &lt;enumeration value="TP"/&gt;
 *     &lt;enumeration value="CM"/&gt;
 *     &lt;enumeration value="SERV"/&gt;
 *     &lt;enumeration value="AT"/&gt;
 *     &lt;enumeration value="ATD"/&gt;
 *     &lt;enumeration value="RFC"/&gt;
 *     &lt;enumeration value="HSS"/&gt;
 *     &lt;enumeration value="AS"/&gt;
 *     &lt;enumeration value="HN"/&gt;
 *     &lt;enumeration value="AP"/&gt;
 *     &lt;enumeration value="PC"/&gt;
 *     &lt;enumeration value="VAL"/&gt;
 *     &lt;enumeration value="TEMP"/&gt;
 *     &lt;enumeration value="PRO"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "voc.EncounterHeading")
@XmlEnum
public enum VocEncounterHeading {


    /**
     * Additional
     * 
     */
    ADD,

    /**
     * Problem
     * 
     */
    PROB,

    /**
     * History
     * 
     */
    HIST,

    /**
     * Examination
     * 
     */
    EXAM,

    /**
     * Family History
     * 
     */
    FH,

    /**
     * Social
     * 
     */
    SOC,

    /**
     * Comment
     * 
     */
    COM,

    /**
     * Result
     * 
     */
    RES,

    /**
     * Medication
     * 
     */
    MED,

    /**
     * Follow up
     * 
     */
    DRY,

    /**
     * Test Request
     * 
     */
    TR,

    /**
     * New Referral
     * 
     */
    REF,

    /**
     * Allergy
     * 
     */
    ALL,

    /**
     * Referral Activity
     * 
     */
    RA,

    /**
     * Signs/Symptoms
     * 
     */
    SS,

    /**
     * Problem Ratings
     * 
     */
    PR,

    /**
     * Health Teaching, Guidance, and Counselling
     * 
     */
    HTGC,

    /**
     * Treatments and Procedures
     * 
     */
    TP,

    /**
     * Case Management
     * 
     */
    CM,

    /**
     * Surveillance
     * 
     */
    SERV,

    /**
     * Assessment Tool
     * 
     */
    AT,

    /**
     * Assessment Tool Details
     * 
     */
    ATD,

    /**
     * Reason for Care
     * 
     */
    RFC,

    /**
     * Hide Sign/Symptom
     * 
     */
    HSS,

    /**
     * Assessment Section
     * 
     */
    AS,

    /**
     * Health Needs (Community)
     * 
     */
    HN,

    /**
     * Action Plan (Community)
     * 
     */
    AP,

    /**
     * Procedure Codes (Community)
     * 
     */
    PC,

    /**
     * Values (Community)
     * 
     */
    VAL,

    /**
     * Template Entry
     * 
     */
    TEMP,

    /**
     * Protocol
     * 
     */
    PRO;

    public String value() {
        return name();
    }

    public static VocEncounterHeading fromValue(String v) {
        return valueOf(v);
    }

}
