//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voc.MessageAuthorSystemType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="voc.MessageAuthorSystemType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="LV"/&gt;
 *     &lt;enumeration value="GV"/&gt;
 *     &lt;enumeration value="PCS"/&gt;
 *     &lt;enumeration value="EMISWEB"/&gt;
 *     &lt;enumeration value="EXT"/&gt;
 *     &lt;enumeration value="GP2GP"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "voc.MessageAuthorSystemType")
@XmlEnum
public enum VocMessageAuthorSystemType {


    /**
     * EMIS LV clinical system
     * 
     */
    LV("LV"),

    /**
     * EMIS GV clinical system
     * 
     */
    GV("GV"),

    /**
     * EMIS PCS clinical system
     * 
     */
    PCS("PCS"),

    /**
     * EMISWEB clinical system
     * 
     */
    EMISWEB("EMISWEB"),

    /**
     * Clinical system external to EMIS
     * 
     */
    EXT("EXT"),
    @XmlEnumValue("GP2GP")
    GP_2_GP("GP2GP");
    private final String value;

    VocMessageAuthorSystemType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VocMessageAuthorSystemType fromValue(String v) {
        for (VocMessageAuthorSystemType c: VocMessageAuthorSystemType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
