//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voc.PopulationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="voc.PopulationType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="PATIENT"/&gt;
 *     &lt;enumeration value="APPOINTMENT"/&gt;
 *     &lt;enumeration value="USER"/&gt;
 *     &lt;enumeration value="DRUG"/&gt;
 *     &lt;enumeration value="APPOINTMENT_SESSION"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "voc.PopulationType")
@XmlEnum
public enum VocPopulationType {


    /**
     * Patient based population e.g. Patient IDs are stored as population results
     * 
     */
    PATIENT,

    /**
     * Appointmnt based population e.g. Appointment Slot IDs are stored as population results
     * 
     */
    APPOINTMENT,

    /**
     * User based population e.g. User IDs are stored as population results
     * 
     */
    USER,

    /**
     * Drug based population e.g. Drug IDs are stored as population results
     * 
     */
    DRUG,
    APPOINTMENT_SESSION;

    public String value() {
        return name();
    }

    public static VocPopulationType fromValue(String v) {
        return valueOf(v);
    }

}
