//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.23 at 09:36:56 AM GMT 
//


package org.endeavourhealth.informationmanager.transforms.eqd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voc.ReminderType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="voc.ReminderType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="UNK"/&gt;
 *     &lt;enumeration value="L"/&gt;
 *     &lt;enumeration value="T"/&gt;
 *     &lt;enumeration value="FX"/&gt;
 *     &lt;enumeration value="EM"/&gt;
 *     &lt;enumeration value="SMS"/&gt;
 *     &lt;enumeration value="RHS"/&gt;
 *     &lt;enumeration value="V"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "voc.ReminderType")
@XmlEnum
public enum VocReminderType {


    /**
     * Unknown
     * 
     */
    UNK,

    /**
     * Letter
     * 
     */
    L,

    /**
     * Telephone
     * 
     */
    T,

    /**
     * Fax
     * 
     */
    FX,

    /**
     * e-mail
     * 
     */
    EM,

    /**
     * SMS (Short Message Service)
     * 
     */
    SMS,

    /**
     * RHS (Right-hand side)
     * 
     */
    RHS,

    /**
     * Verbal
     * 
     */
    V;

    public String value() {
        return name();
    }

    public static VocReminderType fromValue(String v) {
        return valueOf(v);
    }

}
